#!/usr/bin/env node
// @ts-check

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { normalizeDownloadAvailability } from '../src/sites/availability.mjs';

const TOOL_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(TOOL_DIR, '..');

const README_OUTPUT = 'README.md';
const GENERATED_MARKER = '<!-- Generated by tools/generate-readme.mjs; edit the generator instead. -->';

function normalizeSlashes(value) {
  return String(value).replace(/\\/gu, '/');
}

function asPosixPath(...segments) {
  return normalizeSlashes(path.join(...segments));
}

async function readJson(relativePath) {
  return JSON.parse(await readFile(path.join(REPO_ROOT, relativePath), 'utf8'));
}

async function loadContext() {
  const registry = await readJson('config/site-registry.json');
  const capabilities = await readJson('config/site-capabilities.json');
  const hosts = Object.keys(registry.sites ?? {});
  const capabilityHosts = Object.keys(capabilities.sites ?? {});
  if (hosts.join('\n') !== capabilityHosts.join('\n')) {
    throw new Error('site-registry and site-capabilities host order must match before README generation.');
  }
  return {
    siteRows: hosts.map((host) => ({
      host,
      registry: registry.sites?.[host] ?? {},
      capabilities: capabilities.sites?.[host] ?? {},
    })),
  };
}

function stringList(values) {
  return Array.isArray(values)
    ? values.map((value) => String(value).trim()).filter(Boolean)
    : [];
}

function formatList(values, fallback = '无') {
  const list = stringList(values);
  return list.length ? list.join(', ') : fallback;
}

function firstText(...values) {
  for (const value of values) {
    const text = String(value ?? '').trim();
    if (text) {
      return text;
    }
  }
  return null;
}

function publicBuildStatus({ registry, capabilities }) {
  const availability = normalizeDownloadAvailability(registry, capabilities);
  const liveReason = firstText(
    registry.genericLiveBuild?.reasonCode,
    capabilities.genericLiveBuild?.reasonCode,
    registry.siteAccessStatus,
    capabilities.siteAccessStatus,
  );
  if (availability.publicLiveBlocked) {
    return `通用实时构建受阻${liveReason ? ` (${liveReason})` : ''}`;
  }
  if (availability.blockedTaskTypes.length) {
    return '只读元数据；下载执行受阻';
  }
  if (registry.downloadSessionRequirement === 'required') {
    return '已记录站点元数据；声明的下载路径需要授权';
  }
  if (registry.downloadSessionRequirement === 'optional') {
    return '已记录站点元数据；声明的下载路径可能需要授权';
  }
  return '已记录站点元数据';
}

function availableSurface({ registry, capabilities }) {
  const availability = normalizeDownloadAvailability(registry, capabilities);
  if (availability.publicLiveBlocked) {
    return '通用实时构建不可用；仅限授权或本地 HTTP 验证路径';
  }
  const readOnlyFamilies = stringList(capabilities.capabilityFamilies ?? registry.capabilityFamilies)
    .filter((family) => family !== 'download-content');
  const parts = [];
  if (readOnlyFamilies.length) {
    parts.push(`只读能力: ${formatList(readOnlyFamilies)}`);
  }
  if (capabilities.rankingSupported === true) {
    parts.push('排名查询');
  }
  if (availability.availableTaskTypes.length) {
    parts.push(`可用下载: ${formatList(availability.availableTaskTypes)}`);
  }
  if (availability.runtimeDependencies.length) {
    parts.push(`运行依赖: ${formatList(availability.runtimeDependencies)}`);
  }
  return parts.length ? parts.join('; ') : '仅元数据';
}

function blockedOrLimitedSummary({ registry, capabilities }) {
  const availability = normalizeDownloadAvailability(registry, capabilities);
  const parts = [];
  if (availability.declaredTaskTypes.length) {
    parts.push(`已声明下载: ${formatList(availability.declaredTaskTypes)}`);
    parts.push(`可用: ${formatList(availability.availableTaskTypes)}`);
  }
  if (availability.runtimeDependencies.length) {
    parts.push(`运行依赖: ${formatList(availability.runtimeDependencies)}`);
  }
  if (availability.blockedTaskTypes.length) {
    parts.push(`受阻: ${formatList(availability.blockedTaskTypes)}`);
  }
  if (availability.publicLiveBlocked) {
    const reason = availability.genericLiveReasonCode
      ? ` (${availability.genericLiveReasonCode})`
      : '';
    parts.push(`通用实时采集受阻${reason}`);
  }
  if (availability.downloadReasonCode) {
    parts.push(`下载原因: ${availability.downloadReasonCode}`);
  } else if (availability.reasonCode) {
    parts.push(`原因: ${availability.reasonCode}`);
  }
  if (availability.dependencyReasonCodes.length) {
    parts.push(`依赖原因: ${formatList(availability.dependencyReasonCodes)}`);
  }
  return parts.length ? parts.join('; ') : '无记录';
}

function renderSiteTable(siteRows) {
  const rows = siteRows.map((row) => [
    `\`${row.host}\``,
    publicBuildStatus(row),
    availableSurface(row),
    blockedOrLimitedSummary(row),
  ]);
  return [
    '| 主机 | 公开构建状态 | 可用公开能力 | 受阻或受限声明 |',
    '| --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');
}

function renderReadme(context) {
  return `${GENERATED_MARKER}

# SiteForge

SiteForge 用于把公开网站 URL 转换成本地、受治理的站点能力工作区。公开 CLI 保持克制，目前只暴露一个主要入口：

\`\`\`bash
siteforge build https://example.com/
\`\`\`

构建流程会在受约束的站点规则内采集页面证据，将清洗后的证据编译为能力契约，生成仅描述符形式的动作计划，并把已验证产物写入 \`.siteforge/sites/<site_id>/\`。

## 输出内容

- 站点工作区：\`.siteforge/sites/<site_id>/\`。
- 构建报告：\`build_report.user.json\`、\`build_report.user.md\`、\`build_report.debug.json\` 和 \`build_report.json\`。
- 能力契约：页面、风险、会话、Schema、策略和支持的动作。
- 仅描述符计划：记录允许、受阻或需要修复的路径，不执行特权操作。
- 仓库本地 Skill 材料：由已验证的能力证据支撑。

## 架构

仓库保持为一个包和一个公开 CLI。依赖方向固定为 \`entrypoints -> app -> domain\`。Pipeline、Compiler 和 Planner 不绑定具体站点；SiteAdapter 负责站点语义解释；infra 提供 IO、浏览器、认证、网络、进程和 CLI 适配。位于 \`src/entrypoints/\` 下的内部 Node 入口是操作员工具，不属于公开路由。

## 仓库结构

| 路径 | 职责 |
| --- | --- |
| \`src/entrypoints/cli/\` | 公开 CLI 门面；只有 \`siteforge build <url>\` 属于公开命令。 |
| \`src/entrypoints/operator/\` | 内部操作员入口，不通过 \`siteforge\` 对外路由。 |
| \`src/entrypoints/build/\` | 公开 \`siteforge build\` 门面使用的内部构建入口接线。 |
| \`src/entrypoints/pipeline/\` | 操作员流程使用的爬虫辅助入口接线。 |
| \`src/app/pipeline/build/\` | SiteForge 构建编排、生命周期、恢复和验证。 |
| \`src/app/compiler/\` | 证据与能力编译。 |
| \`src/app/planner/\` | 仅描述符计划与策略交接。 |
| \`src/domain/\` | 能力、策略、Schema、风险、会话、产物和生命周期契约。 |
| \`src/sites/\` | SiteAdapter 契约、已知站点辅助逻辑和注册表。 |
| \`src/infra/\` | 浏览器、认证、配置、文件系统、网络、进程和 CLI IO。 |
| \`config/\` | 版本化的稳定站点注册表和能力记录。 |
| \`schema/\` | 发布的 Schema 和 Profile 定义。 |
| \`tests/\` | Node 与 Python 测试、fixture 和回归门禁。 |
| \`tools/\` | README、发布、清理、审计和验证工具。 |

已退役的公开 Web UI、旧能力层、旧 Pipeline engine/runtime/stage 以及旧 kernel 层保持删除状态，并由架构测试守护。下载声明在没有明确记录受约束实现前只作为元数据或站点专用内部路径；受阻占位不会暴露为公开执行能力。

## 已知公开站点记录

稳定配置当前记录了以下主机。表格会区分元数据、可用性、运行依赖和受阻原因，避免把受阻、占位、仅本地验证、需要授权或依赖缺失的记录误表述为通用实时支持。

${renderSiteTable(context.siteRows)}

已删除的内部 catalog 实验不属于公开站点注册表。

## 本地验证

常用本地检查：

\`\`\`bash
npm run readme:check
npm run typecheck
npm run check:syntax
npm run test:node:focused
npm run test:node:all
npm run test:python
npm run scan:secrets
git diff --check
\`\`\`

聚焦测试组包括 \`npm run test:cli\`、\`npm run test:pipeline\`、\`npm run test:capability\` 和 \`npm run test:core\`。提交前可运行 \`npm run clean:outputs\` 清理本地生成的站点数据。

\`npm run typecheck\` 会按 \`tools/typecheck-scope.json\` 中列出的仓库 \`.mjs\` 源码范围运行 TypeScript \`--checkJs\`；该范围不能遗漏仓库源码目录。\`npm run check:syntax\` 会单独自动发现仓库内的 \`.mjs\` 文件，作为语法门禁。

## 安全边界

- 不持久化原始凭证、Cookie、授权头、CSRF 值、会话 ID、浏览器 Profile 或 Token。
- 不实现验证码绕过、反机器人绕过、访问控制绕过、凭证提取或静默提权。
- 不把生成的站点数据写入受跟踪源码。
- 生成产物、日志、下载内容、缓存和浏览器状态必须保持忽略且可清理。

## 发布与版本

发布就绪以证据为准。本地测试通过不等于已打 tag、升级包版本、推送、创建 PR、发布、声明实时能力或完成实时授权验证。不兼容的持久化契约或公开契约变更必须显式升级版本，并补齐对应测试。
`;
}

async function main(argv = process.argv.slice(2)) {
  const check = argv.includes('--check');
  const context = await loadContext();
  const targetPath = path.join(REPO_ROOT, README_OUTPUT);
  const nextText = renderReadme(context).replace(/\r\n/gu, '\n');
  if (check) {
    const currentText = (await readFile(targetPath, 'utf8')).replace(/\r\n/gu, '\n');
    if (currentText !== nextText) {
      throw new Error(`Generated README is stale: ${README_OUTPUT}`);
    }
    console.log('Generated README is current');
    return;
  }
  await writeFile(targetPath, nextText, 'utf8');
  console.log(`Generated ${asPosixPath(README_OUTPUT)}`);
}

await main();
