#!/usr/bin/env node
// @ts-check

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { normalizeDownloadAvailability } from '../src/sites/availability.mjs';

const TOOL_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(TOOL_DIR, '..');

const README_OUTPUT = 'README.md';
const GENERATED_MARKER = '<!-- Generated by tools/generate-readme.mjs; edit the generator instead. -->';

function normalizeSlashes(value) {
  return String(value).replace(/\\/gu, '/');
}

function asPosixPath(...segments) {
  return normalizeSlashes(path.join(...segments));
}

async function readJson(relativePath) {
  return JSON.parse(await readFile(path.join(REPO_ROOT, relativePath), 'utf8'));
}

async function loadContext() {
  const registry = await readJson('config/site-registry.json');
  const capabilities = await readJson('config/site-capabilities.json');
  const hosts = Object.keys(registry.sites ?? {});
  const capabilityHosts = Object.keys(capabilities.sites ?? {});
  if (hosts.join('\n') !== capabilityHosts.join('\n')) {
    throw new Error('site-registry and site-capabilities host order must match before README generation.');
  }
  return {
    siteRows: hosts.map((host) => ({
      host,
      registry: registry.sites?.[host] ?? {},
      capabilities: capabilities.sites?.[host] ?? {},
    })),
  };
}

function stringList(values) {
  return Array.isArray(values)
    ? values.map((value) => String(value).trim()).filter(Boolean)
    : [];
}

function formatList(values, fallback = 'none') {
  const list = stringList(values);
  return list.length ? list.join(', ') : fallback;
}

function firstText(...values) {
  for (const value of values) {
    const text = String(value ?? '').trim();
    if (text) {
      return text;
    }
  }
  return null;
}

function publicBuildStatus({ registry, capabilities }) {
  const availability = normalizeDownloadAvailability(registry, capabilities);
  const liveReason = firstText(
    registry.genericLiveBuild?.reasonCode,
    capabilities.genericLiveBuild?.reasonCode,
    registry.siteAccessStatus,
    capabilities.siteAccessStatus,
  );
  if (availability.publicLiveBlocked) {
    return `generic live build blocked${liveReason ? ` (${liveReason})` : ''}`;
  }
  if (availability.blockedTaskTypes.length) {
    return 'read-only metadata; download execution blocked';
  }
  if (registry.downloadSessionRequirement === 'required') {
    return 'known-site metadata; authorization required for declared download path';
  }
  if (registry.downloadSessionRequirement === 'optional') {
    return 'known-site metadata; authorization may be required for declared download path';
  }
  return 'known-site metadata';
}

function availableSurface({ registry, capabilities }) {
  const availability = normalizeDownloadAvailability(registry, capabilities);
  if (availability.publicLiveBlocked) {
    return 'none through generic live build; use only authorized or local HTTP validation paths';
  }
  const readOnlyFamilies = stringList(capabilities.capabilityFamilies ?? registry.capabilityFamilies)
    .filter((family) => family !== 'download-content');
  const parts = [];
  if (readOnlyFamilies.length) {
    parts.push(`read-only: ${formatList(readOnlyFamilies)}`);
  }
  if (capabilities.rankingSupported === true) {
    parts.push('ranking query');
  }
  if (availability.availableTaskTypes.length) {
    parts.push(`downloads available: ${formatList(availability.availableTaskTypes)}`);
  }
  if (availability.runtimeDependencies.length) {
    parts.push(`requires: ${formatList(availability.runtimeDependencies)}`);
  }
  return parts.length ? parts.join('; ') : 'metadata only';
}

function blockedOrLimitedSummary({ registry, capabilities }) {
  const availability = normalizeDownloadAvailability(registry, capabilities);
  const parts = [];
  if (availability.declaredTaskTypes.length) {
    parts.push(`downloads declared: ${formatList(availability.declaredTaskTypes)}`);
    parts.push(`available: ${formatList(availability.availableTaskTypes)}`);
  }
  if (availability.runtimeDependencies.length) {
    parts.push(`requires: ${formatList(availability.runtimeDependencies)}`);
  }
  if (availability.blockedTaskTypes.length) {
    parts.push(`blocked: ${formatList(availability.blockedTaskTypes)}`);
  }
  if (availability.publicLiveBlocked) {
    const reason = availability.genericLiveReasonCode
      ? ` (${availability.genericLiveReasonCode})`
      : '';
    parts.push(`generic live collection blocked${reason}`);
  }
  if (availability.downloadReasonCode) {
    parts.push(`download reason: ${availability.downloadReasonCode}`);
  } else if (availability.reasonCode) {
    parts.push(`reason: ${availability.reasonCode}`);
  }
  if (availability.dependencyReasonCodes.length) {
    parts.push(`dependency reason: ${formatList(availability.dependencyReasonCodes)}`);
  }
  return parts.length ? parts.join('; ') : 'none recorded';
}

function renderSiteTable(siteRows) {
  const rows = siteRows.map((row) => [
    `\`${row.host}\``,
    publicBuildStatus(row),
    availableSurface(row),
    blockedOrLimitedSummary(row),
  ]);
  return [
    '| Host | Public build status | Available public surface | Blocked or limited declarations |',
    '| --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');
}

function renderReadme(context) {
  return `${GENERATED_MARKER}

# SiteForge

SiteForge turns a public site URL into a local, governed site capability workspace. The public CLI is intentionally small:

\`\`\`bash
siteforge build https://example.com/
\`\`\`

Builds crawl within bounded site rules, compile sanitized evidence into capability contracts, plan descriptor-only actions, and promote verified outputs under \`.siteforge/sites/<site_id>/\`.

## Outputs

- Site workspace: \`.siteforge/sites/<site_id>/\`.
- Build reports: \`build_report.user.json\`, \`build_report.user.md\`, \`build_report.debug.json\`, and \`build_report.json\`.
- Capability contracts: pages, risks, sessions, schemas, policies, and supported actions.
- Descriptor-only plans: allowed, blocked, or remediation paths without privileged execution.
- Repo-local Skill material backed by verified capability evidence.

## Architecture

The repository is one package and one public CLI. Dependency direction stays entrypoints -> app -> domain. Pipeline, Compiler, and Planner stay site-agnostic; SiteAdapters own site interpretation; infra supplies IO, browser, auth, network, process, and CLI adapters. Internal Node entrypoints under \`src/entrypoints/\` are operator tools, not public routes.

## Repository Layout

| Path | Responsibility |
| --- | --- |
| \`src/entrypoints/cli/\` | Public CLI facade; only \`siteforge build <url>\` is public. |
| \`src/entrypoints/operator/\` | Internal operator entrypoints that are not routed through \`siteforge\`. |
| \`src/entrypoints/pipeline/\` | Internal build and crawler-support entrypoint wiring used by operator flows. |
| \`src/app/pipeline/build/\` | SiteForge build orchestration, lifecycle, recovery, and validation. |
| \`src/app/compiler/\` | Evidence and capability compilation. |
| \`src/app/planner/\` | Descriptor-only plans and policy handoff. |
| \`src/domain/\` | Capability, policy, schema, risk, session, artifact, and lifecycle contracts. |
| \`src/sites/\` | SiteAdapter contracts, known-site helpers, and registries. |
| \`src/infra/\` | Browser, auth, config, filesystem, network, process, and CLI IO. |
| \`config/\` | Versioned stable site registry and capability records. |
| \`schema/\` | Published schema/profile definitions. |
| \`tests/\` | Node and Python tests, fixtures, and regression gates. |
| \`tools/\` | README, release, cleanup, audit, and verification tooling. |

Retired public Web UI, legacy capability, legacy pipeline engine/runtime/stage, and legacy kernel layers stay removed and are guarded by architecture tests. Download declarations remain metadata or site-specific internal paths unless a bounded implementation is explicitly recorded; blocked placeholders do not expose public execution.

## Known Public Site Records

Stable config currently keeps records for these hosts. The table separates metadata, availability, runtime dependencies, and blocked reasons so blocked, placeholder, local-validation-only, authorization-required, or dependency-bound records are not presented as generic live support.

${renderSiteTable(context.siteRows)}

Removed internal catalog experiments are not part of the public site registry.

## Verification

Useful local checks:

\`\`\`bash
npm run readme:check
npm run typecheck
npm run check:syntax
npm run test:node:focused
npm run test:node:all
npm run test:python
npm run scan:secrets
git diff --check
\`\`\`

Focused groups are available as \`npm run test:cli\`, \`npm run test:pipeline\`, \`npm run test:capability\`, and \`npm run test:core\`. Use \`npm run clean:outputs\` to remove local generated site data before staging.

\`npm run typecheck\` runs TypeScript \`--checkJs\` across the repository \`.mjs\` source globs listed in \`tools/typecheck-scope.json\`; that scope must not defer repository source directories. \`npm run check:syntax\` separately auto-discovers repository \`.mjs\` files and is a syntax gate.

## Safety

- Do not persist raw credentials, cookies, authorization headers, CSRF values, session ids, browser profiles, or tokens.
- Do not implement CAPTCHA bypass, anti-bot bypass, access-control bypass, credential extraction, or silent privilege expansion.
- Do not write generated site data into tracked source.
- Keep generated outputs, logs, downloads, caches, and browser state ignored and removable.

## Release And Versioning

Release readiness is evidence-based. Local tests do not imply a tag, package version bump, push, PR, publication, live capability claim, or live authenticated validation. Incompatible persisted or public contract changes require an explicit version bump and matching tests.
`;
}

async function main(argv = process.argv.slice(2)) {
  const check = argv.includes('--check');
  const context = await loadContext();
  const targetPath = path.join(REPO_ROOT, README_OUTPUT);
  const nextText = renderReadme(context).replace(/\r\n/gu, '\n');
  if (check) {
    const currentText = (await readFile(targetPath, 'utf8')).replace(/\r\n/gu, '\n');
    if (currentText !== nextText) {
      throw new Error(`Generated README is stale: ${README_OUTPUT}`);
    }
    console.log('Generated README is current');
    return;
  }
  await writeFile(targetPath, nextText, 'utf8');
  console.log(`Generated ${asPosixPath(README_OUTPUT)}`);
}

await main();
