import test from 'node:test';
import assert from 'node:assert/strict';

import {
  COLLECTION_OUTCOME_LIMIT,
  COLLECTION_OUTCOME_STAGE_STATUSES,
  collectUnsuccessfulCollections,
  collectionOutcomeKindForStage,
  collectionOutcomeReason,
  collectionOutcomeReasonCodeForStage,
  compareCollectionOutcomes,
  isDebugOnlyCapability,
} from '../../src/app/pipeline/build/collection-outcomes.mjs';
import {
  displayBuildWarning,
  renderCollectionOutcomeTable,
} from '../../src/app/pipeline/build/build-report-display.mjs';

test('SiteForge collection outcome constants describe report truncation and stage statuses', () => {
  assert.equal(COLLECTION_OUTCOME_LIMIT, 40);
  assert.deepEqual(COLLECTION_OUTCOME_STAGE_STATUSES, ['blocked', 'failed', 'skipped']);
});

test('SiteForge collection outcome stage kinds stay report-oriented and deterministic', () => {
  assert.equal(collectionOutcomeKindForStage('buildSiteGraph'), 'node');
  assert.equal(collectionOutcomeKindForStage('discoverInteractions'), 'affordance');
  assert.equal(collectionOutcomeKindForStage('generateIntents'), 'capability');
  assert.equal(collectionOutcomeKindForStage('unknownStage'), 'stage');
});

test('SiteForge collection outcome reasons preserve user-facing recovery semantics', () => {
  assert.match(
    collectionOutcomeReason('dynamic-unsupported', 'crawlRendered'),
    /Chromium browser/u,
  );
  assert.match(
    collectionOutcomeReason('dynamic-unsupported', 'captureNetworkTraces'),
    /Network summary was not requested/u,
  );
  assert.equal(
    collectionOutcomeReason(''),
    'Not enough verified evidence to promote this item.',
  );
  assert.equal(
    collectionOutcomeReason('capability-specific-evidence-required'),
    'Capability was discovered, but capability-specific evidence is still required before activation.',
  );
});

test('SiteForge collection outcome reason codes derive from stage records', () => {
  assert.equal(collectionOutcomeReasonCodeForStage({ reasonCode: 'custom' }), 'custom');
  assert.equal(collectionOutcomeReasonCodeForStage({ status: 'failed' }), 'stage-failed');
  assert.equal(collectionOutcomeReasonCodeForStage({ status: 'blocked' }), 'stage-blocked');
  assert.equal(collectionOutcomeReasonCodeForStage({ status: 'skipped' }), 'stage-skipped');
});

test('SiteForge collection outcome ordering keeps build and stage failures first', () => {
  const outcomes = [
    { kind: 'capability', status: 'active', target: 'read timeline' },
    { kind: 'affordance', status: 'failed', target: 'button' },
    { kind: 'build', status: 'failed', target: 'build' },
    { kind: 'capability', status: 'candidate', target: 'candidate read' },
    { kind: 'stage', status: 'blocked', target: 'crawlRendered' },
    { kind: 'node', status: 'failed', target: 'home' },
  ].sort(compareCollectionOutcomes);

  assert.deepEqual(outcomes.map((outcome) => outcome.kind), [
    'build',
    'stage',
    'node',
    'affordance',
    'capability',
    'capability',
  ]);
  assert.equal(outcomes[4].target, 'candidate read');
});

test('SiteForge collection outcome aggregation ignores active and debug-only capabilities', () => {
  assert.equal(isDebugOnlyCapability({ status: 'candidate' }), true);
  assert.equal(isDebugOnlyCapability({ enabled_status: 'candidate_debug_only' }), true);
  assert.equal(isDebugOnlyCapability({
    autoGenerated: true,
    informational: true,
    enabled_status: 'disabled',
    risk_level: 'read_public_low',
  }), true);
  assert.equal(isDebugOnlyCapability({ status: 'disabled', enabled_status: 'disabled' }), false);

  const result = collectUnsuccessfulCollections(
    {
      discoverCapabilities: {
        capabilities: [
          { name: 'active read', status: 'active' },
          { name: 'debug candidate', status: 'candidate' },
          {
            name: 'selected blocked read',
            status: 'disabled',
            activationBlockedReason: 'capability-specific-evidence-required',
            selectedBySetup: true,
            browserSeedBacked: true,
            safetyLevel: 'read_only',
          },
        ],
      },
    },
    {
      crawlRendered: { status: 'skipped', reasonCode: 'dynamic-unsupported' },
    },
    'failed',
    { stage: 'verifySkill', reasonCode: 'validation-failed' },
  );

  assert.equal(result.total, 3);
  assert.equal(result.truncated, false);
  assert.deepEqual(result.unsuccessful.map((item) => `${item.kind}:${item.target}:${item.reasonCode}`), [
    'build:verifySkill:validation-failed',
    'stage:crawlRendered:dynamic-unsupported',
    'capability:selected blocked read:capability-specific-evidence-required',
  ]);
  assert.equal(result.unsuccessful[2].selectedBySetup, true);
  assert.equal(result.unsuccessful[2].browserSeedBacked, true);
});

test('SiteForge collection outcome report display stays sanitized and user-facing', () => {
  assert.equal(
    displayBuildWarning('network-fetch-failed'),
    'Network fetch failed; raw error details were not saved.',
  );
  assert.match(
    displayBuildWarning('Skipped because crawlRendered skipped.'),
    /^Skipped because stage crawlRendered status is /u,
  );

  const rows = renderCollectionOutcomeTable([{
    kind: 'capability',
    target: 'read|timeline\nlatest',
    status: 'blocked',
    reasonCode: 'capability-specific-evidence-required',
  }, {
    kind: 'stage',
    target: '',
    status: 'skipped',
    reasonCode: 'network-fetch-failed',
  }]);

  assert.deepEqual(rows.slice(0, 2), [
    '  | Type | Target | Status | Reason |',
    '  | --- | --- | --- | --- |',
  ]);
  assert.match(rows[2], /read\\\|timeline latest/u);
  assert.match(rows[2], /Capability-specific evidence is missing\./u);
  assert.match(rows[3], /Network fetch failed; no verifiable page evidence was collected\./u);
});
